name = "rollback"
description = "Reverts the last change made to the project."
command = "/home/matt/PycharmProjects/matt_raio_bot_constraints/venv/bin/python -c \"import asyncio; from slash_commands import rollback; asyncio.run(rollback())""